#!/usr/bin/env bash
# Configure Nginx's HTTP response contains a header (on web-01 and web-02)
# 	The name of the custom HTTP header is X-Served-By
# 	The value of the HTTP header is the hostname of the server
# shellcheck disable=SC2154

hs=$(hostname)
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html/;
     index       index.html index.htm;
     add_header X-Served-By "$hs";
}" > /etc/nginx/sites-available/default

service nginx restart
