#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
#	Configure HAproxy so that it send traffic to web-01 and web-02
#	Distribute requests using a roundrobin algorithm
#	Make sure that HAproxy can be managed via an init script
#	Make sure that servers are configured with right hostnames

apt-get update
apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
printf %s "frontend myfrontend
	mode http
	bind 127.0.0.1:80
	default_backend original_two_servers

backend original_two_servers
	balance roundrobin
	mode http
	server 57576-web-01 34.224.62.19:80 check
	server 57576-web-02 54.166.130.58:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
