#!/usr/bin/env bash
# A bash script that configures a server with nginx running, and
# istening on port 80 of all active IPv4 IPs

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
