#!/usr/bin/env bash
#Displays 'Best School' 10 times and in the 9th iteration displays 'hi'
i=0
while ((i < 10))
do
	if [ $i == 8 ]; then
		echo 'Best School'
		echo 'Hi'
	else
		echo 'Best School'
	fi
	((i++))
done
