#!/usr/bin/env bash
#Displays numbers 1-20, but displays 'bad luck from China' after 4,
#'bad luck from Japan' after 9, and 'bad luck from Italy' after 17
i=1
while ((i <= 20))
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac	
	((i++))
done
